export const MOCK_EVENTS = [
  {
    id: 'e1',
    name: 'Andreessen Horowitz AI Demo Night',
    description: 'Top AI founders pitch to a16z partners and LPs. Networking heavy, investor density high.',
    location: 'Mission District, SF',
    address: '2865 16th St, San Francisco, CA',
    lat: 37.7651,
    lng: -122.4194,
    start_time: '19:00',
    end_time: '21:30',
    tags: ['AI', 'investors', 'founders', 'demo'],
    attendee_count: 280,
    luma_url: 'https://lu.ma/a16z-ai-demo'
  },
  {
    id: 'e2',
    name: 'Founders & Operators SF Mixer',
    description: 'Casual drinks for Series A+ founders and senior operators. No pitching allowed.',
    location: 'SoMa, SF',
    address: '1355 Market St, San Francisco, CA',
    lat: 37.7762,
    lng: -122.4167,
    start_time: '18:30',
    end_time: '21:00',
    tags: ['networking', 'founders', 'operators', 'Series A'],
    attendee_count: 150,
    luma_url: 'https://lu.ma/founders-operators-sf'
  },
  {
    id: 'e3',
    name: 'Late Night Builders Hackathon Kickoff',
    description: 'Build something in 8 hours. Vibe: creative chaos. Category: AI tooling for devs.',
    location: 'Hayes Valley, SF',
    address: '601 Eddy St, San Francisco, CA',
    lat: 37.7808,
    lng: -122.4225,
    start_time: '21:00',
    end_time: '05:00',
    tags: ['hackathon', 'builders', 'AI', 'developers', 'late night'],
    attendee_count: 90,
    luma_url: 'https://lu.ma/builders-hack-sf'
  },
  {
    id: 'e4',
    name: 'Crypto × AI Research Symposium',
    description: 'Academic-style talks on ZK proofs, agent economies, and on-chain AI inference.',
    location: 'Financial District, SF',
    address: '100 Bush St, San Francisco, CA',
    lat: 37.7915,
    lng: -122.4005,
    start_time: '17:00',
    end_time: '20:00',
    tags: ['crypto', 'AI', 'research', 'ZK', 'investors'],
    attendee_count: 200,
    luma_url: 'https://lu.ma/crypto-ai-symposium'
  },
  {
    id: 'e5',
    name: 'YC Alumni SF Happy Hour',
    description: 'Monthly YC alumni gather. Mix of current batch and veteran founders. High signal.',
    location: 'Potrero Hill, SF',
    address: '816 Tennessee St, San Francisco, CA',
    lat: 37.7601,
    lng: -122.3965,
    start_time: '18:00',
    end_time: '20:30',
    tags: ['YC', 'founders', 'alumni', 'networking'],
    attendee_count: 175,
    luma_url: 'https://lu.ma/yc-alumni-sf'
  },
  {
    id: 'e6',
    name: 'Product Hunt SF Launch Party',
    description: 'Celebrate this week\'s top launches. Makers, early adopters, and press in attendance.',
    location: 'Tenderloin, SF',
    address: '522 Larkin St, San Francisco, CA',
    lat: 37.7811,
    lng: -122.4171,
    start_time: '20:00',
    end_time: '23:00',
    tags: ['product', 'launch', 'makers', 'press', 'community'],
    attendee_count: 130,
    luma_url: 'https://lu.ma/ph-sf-launch'
  },
  {
    id: 'e7',
    name: 'Women in AI Leadership Dinner',
    description: 'Curated dinner for 40 women leading AI teams at top companies. Invite only, apply to attend.',
    location: 'Nob Hill, SF',
    address: '1300 Mason St, San Francisco, CA',
    lat: 37.7924,
    lng: -122.4168,
    start_time: '19:30',
    end_time: '22:00',
    tags: ['AI', 'leadership', 'diversity', 'dinner', 'curated'],
    attendee_count: 40,
    luma_url: 'https://lu.ma/women-ai-dinner'
  },
  {
    id: 'e8',
    name: 'Startup Grind SF: Future of Work',
    description: 'Panel with Rippling, Remote, and Notion on how AI is restructuring the knowledge economy.',
    location: 'Union Square, SF',
    address: '333 Post St, San Francisco, CA',
    lat: 37.7879,
    lng: -122.4074,
    start_time: '17:30',
    end_time: '19:30',
    tags: ['future of work', 'AI', 'panel', 'enterprise', 'SaaS'],
    attendee_count: 220,
    luma_url: 'https://lu.ma/startup-grind-sf'
  },
  {
    id: 'e9',
    name: 'SF Web3 × Farcaster Social Night',
    description: 'IRL meetup for Farcaster power users and builders. Crypto-native crowd, good vibes.',
    location: 'North Beach, SF',
    address: '255 Columbus Ave, San Francisco, CA',
    lat: 37.7988,
    lng: -122.4070,
    start_time: '20:30',
    end_time: '23:30',
    tags: ['web3', 'crypto', 'Farcaster', 'social', 'community'],
    attendee_count: 85,
    luma_url: 'https://lu.ma/farcaster-sf'
  },
  {
    id: 'e10',
    name: 'Open Source AI Infrastructure Meetup',
    description: 'MLOps, vLLM, and LangChain contributors share what\'s shipping. Engineers only vibes.',
    location: 'Mission District, SF',
    address: '2161 Mission St, San Francisco, CA',
    lat: 37.7609,
    lng: -122.4186,
    start_time: '18:00',
    end_time: '20:30',
    tags: ['open source', 'AI', 'infrastructure', 'MLOps', 'engineers', 'developers'],
    attendee_count: 110,
    luma_url: 'https://lu.ma/oss-ai-infra-sf'
  }
];

export const SF_CENTER = { lat: 37.7749, lng: -122.4194 };
